sudo: required
dist: precise
language: perl
perl:
  - "5.18"
rvm:
  - 2.3
addons: 
    ssh_known_hosts: github.com
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "skynet@open.qa"
before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/trusty.list
  - sudo apt-get update -qq
  - sudo apt-get install libgmp3-dev libdbus-1-dev
install:
  - gem install sass asciidoctor pygments.rb
  - gem install asciidoctor-pdf --pre
  - cpanm -nq --installdeps --with-feature=coverage .
script:
  # 'coverage-coveralls' calls checkstyle, tests and coverage analysis in
  # coveralls format
  - GH_PUBLISH=true bash script/generate-documentation
  - MOJO_TMPDIR=$(mktemp -d) make coverage-coveralls coverage-check
after_failure:
  - cat /tmp/openqa-debug.log
